# Generated by Django 5.1.3 on 2025-01-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tdate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
